Repository IT-Cotato/9th-Growing-Pain-FE, pull requests merged in 2024-07, with the labels that each got.

#11 [UPDATE] 라우팅 & 사이드바 수정
  src/components/Layout.jsx
  src/components/ProtectedRoutes.jsx
  src/components/Sidebar.jsx
  src/pages/About.jsx
  src/pages/Dashboard.jsx
  src/pages/Detail.jsx
  src/pages/Login.jsx
  src/pages/Record.jsx
  src/pages/Signup.jsx
  src/routes/Router.jsx
  tailwind.config.js
Labels: 🌿haydenCho, ✔️FIX

#10 [FEAT] 로그인, 회원가입
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/defaultProfile.png
  src/assets/images/googleLogin.png
  src/assets/images/kakaoLogin.png
  src/assets/images/profile.jpeg
  src/components/Button.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/InputField.jsx
  src/components/Layout.jsx
  src/components/ProtectedRoutes.jsx
  src/components/Sidebar.jsx
  src/pages/FindID.jsx
  src/pages/FindPassword.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/routes/Router.jsx
Labels: ✨FEAT, 🦕 yongaricode

#14 [UPDATE] 임시 데이터 생성
  src/App.jsx
  src/components/Sidebar.jsx
  src/pages/AddInfo.jsx
  src/pages/EditActivity.jsx
  src/pages/Record.jsx
  src/pages/Signup.jsx
  src/routes/Router.jsx
Labels: 🌿haydenCho

#15 [UPDATE] 유저 데이터 구조 수정
  src/App.jsx
Labels: 🌈 STYLE, 🌿haydenCho

#16 [FEAT] 성장기록 페이지 구현 및 폰트 적용
  package-lock.json
  package.json
  public/images/공모전.png
  public/images/대외활동.png
  public/images/동아리.png
  public/images/봉사활동.png
  public/images/여분통.png
  public/images/프로젝트.png
  public/vite.svg
  src/App.jsx
  src/components/ActivityCategory.jsx
  src/components/GrowthApplyItem.jsx
  src/components/Sidebar.jsx
  src/components/UseCalendar.css
  src/components/UseCalendar.jsx
  src/fonts/Pretendard-Bold.otf
  src/fonts/Pretendard-Medium.otf
  src/fonts/Pretendard-Regular.otf
  src/index.css
  src/pages/GrowthRecord.jsx
  src/utils/.gitkeep
  src/utils/activity-info.js
  src/utils/getDDay.js
  tailwind.config.js
Labels: ✨FEAT, 🌿haydenCho

#17 [FEAT, UPDATE] 공통 컴포넌트 수정 및 개발
  src/components/Button.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/InputField.jsx
  src/components/MemoField.jsx
Labels: ✨FEAT, 🦕 yongaricode, ✔️FIX

#18 [FEAT] 활동기록 페이지 UI 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/ActivityCategory.jsx
  src/components/ActivityItem.jsx
  src/components/GrowthApplyItem.jsx
  src/components/ProgressBar.jsx
  src/components/Sidebar.jsx
  src/fonts/Pretendard-SemiBold.otf
  src/index.css
  src/pages/ActivityRecord.jsx
  src/pages/GrowthRecord.jsx
  src/routes/Router.jsx
  src/utils/activity-info.js
  tailwind.config.js
Labels: ✨FEAT, 🌿haydenCho

#19 [FEAT] 지원현황 페이지 UI 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/ApplyRecordItem.jsx
  src/components/GrowthApplyItem.jsx
  src/components/UseCalendar.jsx
  src/pages/ApplyRecord.jsx
  src/pages/GrowthRecord.jsx
Labels: ✨FEAT, 🌿haydenCho

#20 [FEAT] 비밀번호 찾기, 회원가입 성공 페이지 UI 구현
  src/pages/FindPassword.jsx
  src/pages/FindPassword2.jsx
  src/pages/SignupSuccess.jsx
  src/routes/Router.jsx
Labels: ✨FEAT, 🦕 yongaricode

#29 [UPDATE] 비밀번호 찾기 UI, 사이드바 수정
  src/components/Button.jsx
  src/components/Sidebar.jsx
  src/pages/FindPassword2.jsx
Labels: 🦕 yongaricode

#30 [UPDATE] 커뮤니티 UI 수정, Refactoring, 전체 페이지 비율화
  src/App.css
  src/App.jsx
  src/components/Button.jsx
  src/components/Layout.jsx
  src/components/MemoField.jsx
  src/components/MenuBar.jsx
  src/components/PostForm.jsx
  src/components/PostItem.jsx
  src/components/PostList.jsx
  src/components/Sidebar.jsx
  src/pages/Dashboard.jsx
  src/pages/FreeCommunity.jsx
  src/pages/GrowthRecord.jsx
  src/pages/MemberCommunity.jsx
  src/pages/Notification.jsx
  src/pages/PortfolioCommunity.jsx
  src/pages/TotalCommunity.jsx
  src/routes/Router.jsx
  tailwind.config.js
Labels: ✨FEAT, 🛠️REFACTOR, 🦕 yongaricode

#31 [UPDATE] 성장기록, 지원현황, 활동기록, 마이페이지 비율 및 UI 수정
  public/images/공모전.png
  public/images/대외활동.png
  public/images/동아리.png
  public/images/봉사활동.png
  public/images/여분통.png
  public/images/지원현황_광고.png
  public/images/프로젝트.png
  src/App.jsx
  src/components/ActivityCategory.jsx
  src/components/ActivityItem.jsx
  src/components/ApplyRecordItem.jsx
  src/components/GrowthApplyItem.jsx
  src/components/Layout.jsx
  src/components/MyCommunityItem.jsx
  src/components/Sidebar.jsx
  src/components/UseCalendar.css
  src/pages/ActivityRecord.jsx
  src/pages/ApplyRecord.jsx
  src/pages/GrowthRecord.jsx
  src/pages/Message.jsx
  src/pages/MyCommunity.jsx
  src/pages/MyPage.jsx
  src/pages/Setting.jsx
  src/routes/Router.jsx
  tailwind.config.js
Labels: 🛠️REFACTOR, 🌿haydenCho

#32 [UPDATE] 마이페이지 UI 비율 수정
  src/components/HeaderMyPage.jsx
  src/components/InputField.jsx
  src/components/MenubarMyPage.jsx
  src/pages/EditMyAbout.jsx
  src/pages/EditMyInfo.jsx
  src/pages/MyCommunity.jsx
  src/pages/MyPage.jsx
  src/pages/Setting.jsx
  src/pages/Support.jsx
Labels: 🛠️REFACTOR, 🌿haydenCho

#33 [UPDATE] 성장기록, 지원현황, 활동기록 UI 비율 수정
  src/components/ActivityItem.jsx
  src/components/GrowthApplyItem.jsx
  src/components/UseCalendar.css
  src/pages/ActivityRecord.jsx
  src/pages/GrowthRecord.jsx
Labels: 🛠️REFACTOR, 🌿haydenCho

#34 [FEAT] 지원현황 상세 편집 페이지 UI 구현
  src/components/EditApply.jsx
  src/components/InputField.jsx
  src/components/MemoField.jsx
  src/pages/Detail.jsx
  src/pages/Record.jsx
  tailwind.config.js
Labels: ✨FEAT, 🌿haydenCho

#35 [UPDATE] Community UI 수정, Login, Signup Mock Server API 생성
  package-lock.json
  package.json
  src/components/PostForm.jsx
  src/components/PostItem.jsx
  src/components/PostList.jsx
  src/pages/FindPassword.jsx
  src/pages/FindPassword2.jsx
  src/pages/Login.jsx
  src/pages/Signup.jsx
  src/pages/TotalCommunity.jsx
Labels: ✨FEAT, 🦕 yongaricode

#37 [FEAT] 지원현황 편집 컴포넌트 UI
  package-lock.json
  package.json
  src/App.jsx
  src/components/DatePicker.css
  src/components/EditApply.jsx
  src/components/InputField.jsx
  src/components/MemoField.jsx
  src/components/MenubarMyPage.jsx
  src/components/Sidebar.jsx
  src/components/Toggle.jsx
  src/pages/Login.jsx
  src/pages/MyCommunity.jsx
  src/routes/Router.jsx
  tailwind.config.js
Labels: ✨FEAT, 🌿haydenCho

#38 [FEAT] 활동기록 편집 컴포넌트 UI
  src/components/ActivityItem.jsx
  src/components/EditActivity.jsx
  src/components/MemoField.jsx
  src/components/Sidebar.jsx
  src/pages/ActivityRecord.jsx
  src/pages/DetailActivity.jsx
  src/pages/EditActivity.jsx
  src/pages/NewActivity.jsx
  src/routes/Router.jsx
Labels: ✨FEAT, 🌿haydenCho

#39 [UPDATE] 마이페이지 및 지원현황 페이지 비율
  src/components/ApplyRecordItem.jsx
  src/components/MyCommunityItem.jsx
  src/pages/ApplyRecord.jsx
  src/pages/MyCommunity.jsx
Labels: 🌿haydenCho, ✔️FIX

#40 [UPDATE] 마이페이지 설정 UI
  src/components/InputField.jsx
  src/pages/Setting.jsx
Labels: 🌿haydenCho
