Repository IT-Cotato/9th-Growing-Pain-FE, pull requests merged in 2024-08, with the labels that each got.

#42 [UPDATE] 커뮤니티 태그 수정, 댓글창 모달 url 설정
  package-lock.json
  package.json
  src/components/CategoryTag.jsx
  src/components/CommentModal.jsx
  src/components/PostItem.jsx
  src/pages/TotalCommunity.jsx
  src/utils/atoms.js
Labels: ✨FEAT, 🦕 yongaricode

#46 [FEAT] 마이페이지 알림 페이지 UI
  src/App.jsx
  src/components/ApplyRecordItem.jsx
  src/components/NotificationItem.jsx
  src/pages/ApplyRecord.jsx
  src/pages/Notification.jsx
  src/utils/calculateTimeAgo.js
Labels: ✨FEAT, 🌿haydenCho

#47 [UPDATE] 알림 아이템 클릭시 페이지 이동 문제 수정
  src/components/NotificationItem.jsx
  src/pages/Notification.jsx
  src/utils/calculateTimeAge.js
Labels: 🌿haydenCho

#49 [FEAT] 활동기록 편집 컴포넌트 사용 및 Memofield 컴포넌트 수정
  src/App.jsx
  src/components/ApplyRecordItem.jsx
  src/components/Button.jsx
  src/components/EditActivity.jsx
  src/components/EditApply.jsx
  src/components/MemoField.jsx
  src/components/Toggle.jsx
  src/pages/Detail.jsx
  src/pages/DetailActivity.jsx
  src/pages/NewActivity.jsx
  src/pages/Record.jsx
Labels: ✨FEAT, 🌿haydenCho

#50 [UPDATE] 디데이 계산 등 수정
  src/App.jsx
  src/components/ActivityItem.jsx
  src/components/EditApply.jsx
  src/components/InputField.jsx
  src/pages/ActivityRecord.jsx
  src/pages/DetailActivity.jsx
  src/pages/Notification.jsx
  src/utils/activity-info.js
  src/utils/getDDay.js
Labels: 🌿haydenCho

#51 [UPDATE] 커뮤니티 기능/UI 추가 & 공통 컴포넌트 MemoField 수정
  src/components/CommentModal.jsx
  src/components/MemoField.jsx
  src/pages/TotalCommunity.jsx
Labels: ✨FEAT, 🦕 yongaricode

#53 [FEAT] 대쉬보드 UI
  public/images/대쉬보드_배너.png
  public/images/커뮤니티_확성기.png
  src/App.jsx
  src/components/ActivityCategory.jsx
  src/components/Button.jsx
  src/components/DashToday.jsx
  src/components/EditActivity.jsx
  src/components/GrowthApplyItem.jsx
  src/components/InputField.jsx
  src/components/UseCalendar.css
  src/pages/ActivityRecord.jsx
  src/pages/Dashboard.jsx
  src/pages/GrowthRecord.jsx
  src/pages/Notification.jsx
  src/utils/getDDay.js
  src/utils/today-talk.js
  tailwind.config.js
Labels: ✨FEAT, 🌿haydenCho

#55 [UPDATE] 지원현황 편집 컴포넌트 완성 및 사용
  src/App.jsx
  src/components/ApplyRecordItem.jsx
  src/components/EditApply.jsx
  src/components/InputField.jsx
  src/components/Toggle.jsx
  src/pages/Dashboard.jsx
  src/pages/Detail.jsx
  src/pages/Record.jsx
Labels: ✨FEAT, 🛠️REFACTOR, 🌿haydenCho

#59 [FEAT] 지원현황 생성, 수정 기능
  src/components/EditApply.jsx
  src/pages/Detail.jsx
  src/pages/Record.jsx
Labels: ✨FEAT, 🌿haydenCho

#60 [UPDATE] 기록하기 페이지 데이터 초기화 에러 해결
  src/components/EditApply.jsx
  src/pages/Detail.jsx
  src/pages/Record.jsx
Labels: 🌿haydenCho, ✔️FIX

#61 [UPDATE] 지원현황 임시 데이터 구조 수정
  src/App.jsx
  src/pages/ApplyRecord.jsx
  src/pages/Dashboard.jsx
  src/pages/Detail.jsx
  src/pages/GrowthRecord.jsx
  src/pages/Record.jsx
Labels: 🛠️REFACTOR, 🌿haydenCho

#62 [FEAT] 지원현황 리스트 조회 기능 연결
  src/pages/ApplyRecord.jsx
  src/pages/Dashboard.jsx
  src/pages/GrowthRecord.jsx
Labels: ✨FEAT, 🛠️REFACTOR, 🌿haydenCho

#64 [UPDATE] 지원현황 기능 및 캘린더 데이터 변환
  src/assets/images/CommunityBanner.png
  src/components/EditApply.jsx
  src/components/UseCalendar.jsx
  src/pages/ApplyRecord.jsx
  src/pages/Dashboard.jsx
  src/pages/GrowthRecord.jsx
  src/pages/Record.jsx
  src/pages/Signup.jsx
Labels: 🌿haydenCho, ✔️FIX

#69 [FEAT] axios 인스턴스 생성 및 지원현황 등록 연동
  src/components/NewApply.jsx
  src/pages/ApplyRecord.jsx
  src/pages/Dashboard.jsx
  src/pages/Detail.jsx
  src/pages/GrowthRecord.jsx
  src/pages/Record.jsx
  src/routes/Router.jsx
  src/utils/instance.js
  src/utils/interceptor.js
Labels: ✨FEAT, 🛠️REFACTOR, 🌿haydenCho

#71 [FEAT] 프로텍트 라우터 설정
  src/App.jsx
  src/api/instance.js
  src/components/ProtectedRoutes.jsx
  src/pages/Login.jsx
  src/routes/Router.jsx
Labels: ✨FEAT, 🌿haydenCho

#72 [FEAT] 지원현황 조회 기능 연동
  src/components/ApplyRecordItem.jsx
  src/components/InputField.jsx
  src/components/NewApply.jsx
  src/pages/ApplyRecord.jsx
  src/pages/Dashboard.jsx
  src/pages/GrowthRecord.jsx
  src/utils/getDDay.js
  tailwind.config.js
Labels: ✨FEAT, 🌿haydenCho

#73 [FEAT] 지원현황 상세 조회 기능 연동
  src/components/ActivityCategory.jsx
  src/pages/Detail.jsx
  src/pages/GrowthRecord.jsx
Labels: ✨FEAT, 🌿haydenCho

#74 [FEAT] 활동기록 등록, 리스트 조회 연동 및 로그아웃 버튼 UI 추가
  src/components/ActivityItem.jsx
  src/components/EditActivity.jsx
  src/components/MemoField.jsx
  src/components/Sidebar.jsx
  src/pages/ActivityRecord.jsx
  src/pages/ApplyRecord.jsx
  src/pages/Dashboard.jsx
  src/pages/GrowthRecord.jsx
  src/pages/NewActivity.jsx
  src/routes/Router.jsx
Labels: ✨FEAT, 🌿haydenCho

#75 [FIX] 응답 데이터에 맞게 토큰 저장 수정
  src/api/instance.js
  src/pages/Login.jsx
Labels: 🌿haydenCho, ✔️FIX

#76 [FEAT] 지원현황 활동기록 기능 연동
  src/components/ActivityItem.jsx
  src/components/ApplyRecordItem.jsx
  src/components/EditActivity.jsx
  src/components/EditApply.jsx
  src/pages/ActivityRecord.jsx
  src/pages/Detail.jsx
  src/pages/DetailActivity.jsx
  src/pages/NewActivity.jsx
  src/pages/Record.jsx
Labels: ✨FEAT, 🌿haydenCho

#78 [FEAT] 지원현황 페이지 삭제 구현
  src/components/ActivityItem.jsx
  src/components/EditApply.jsx
  src/components/NewApply.jsx
  src/pages/ActivityRecord.jsx
  src/pages/DetailActivity.jsx
Labels: ✨FEAT, 🌿haydenCho

#80 [FEAT] 마이페이지 정보 조회 및 수정 기능 연동
  src/components/HeaderMyPage.jsx
  src/components/InputField.jsx
  src/pages/EditMyAbout.jsx
  src/pages/EditMyInfo.jsx
  src/pages/MyPage.jsx
Labels: ✨FEAT, 🌿haydenCho

#81 [FEAT] 마이페이지 커뮤니티 조회 및 삭제 연동
  src/api/instance.js
  src/components/MyCommunityItem.jsx
  src/pages/MyCommunity.jsx
Labels: ✨FEAT, 🌿haydenCho

#83 [FEAT] 마이페이지 커뮤니티 활동 연동 완료 및 UI 수정
  src/api/instance.js
  src/components/MyCommunityItem.jsx
  src/pages/MyCommunity.jsx
  src/pages/MyPage.jsx
  src/pages/Setting.jsx
Labels: ✨FEAT, 🌿haydenCho

#84 [FEAT] 마이페이지 비밀번호 변경 연동 및 스크롤바 커스텀
  src/components/ActivityItem.jsx
  src/index.css
  src/pages/ActivityRecord.jsx
  src/pages/Setting.jsx
Labels: ✨FEAT, 🌿haydenCho

#85 [FEAT] 마이페이지 정보 수정 기능 연동 완료
  src/components/EditApply.jsx
  src/components/NewApply.jsx
  src/pages/ActivityRecord.jsx
  src/pages/ApplyRecord.jsx
  src/pages/Detail.jsx
  src/pages/EditMyAbout.jsx
  src/pages/EditMyInfo.jsx
  src/pages/Record.jsx
  src/pages/Setting.jsx
Labels: ✨FEAT, 🌿haydenCho

#86 [UPDATE] 로고, 페이지 타이틀 및 파비콘 설정
  index.html
  public/images/favicon.ico
  public/images/favicon_logo.ico
  src/assets/images/logo.png
  src/components/Header.jsx
  src/components/Sidebar.jsx
Labels: 🌈 STYLE, 🌿haydenCho

#88 [FEAT] 메인 홈 구현 및 지원현황 수정
  public/images/main_1.png
  public/images/main_2.png
  public/images/main_3.png
  public/images/main_4.png
  public/images/main_5.png
  src/components/Button.jsx
  src/components/EditApply.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/pages/Detail.jsx
  src/pages/Main.jsx
  tailwind.config.js
Labels: ✨FEAT, 🌿haydenCho, ✔️FIX

#89 [UPDATE] App.jsx 목데이터 삭제
  src/App.jsx
  src/pages/ApplyRecord.jsx
  src/pages/MyCommunity.jsx
  src/pages/Support.jsx
Labels: 🛠️REFACTOR, 🌿haydenCho

#90 [FEAT] 메인홈 애니메이션 및 캘린더 UI 수정
  package-lock.json
  package.json
  src/components/ActivityCategory.jsx
  src/components/Button.jsx
  src/components/UseCalendar.css
  src/pages/Dashboard.jsx
  src/pages/GrowthRecord.jsx
  src/pages/Main.jsx
Labels: ✨FEAT, 🌿haydenCho

#91 [FEAT] 마이페이지 댓글 알림 연동
  src/api/instance.js
  src/components/NotificationItem.jsx
  src/pages/Notification.jsx
  src/pages/Setting.jsx
  src/utils/calculateTimeAge.js
Labels: ✨FEAT, 🌿haydenCho

#92 [FEAT] 마이페이지 지원현황 알림 연동
  src/components/EditApply.jsx
  src/components/NewApply.jsx
  src/pages/Notification.jsx
  src/pages/Record.jsx
Labels: ✨FEAT, 🌿haydenCho

#93 [UPDATE] 알림 페이지 스크롤바 설정
  src/pages/Notification.jsx
Labels: ✨FEAT, 🌿haydenCho

#96 [UPDATE] 마이페이지 메모필드로 수정
  src/components/InputField.jsx
  src/components/MemoField.jsx
  src/pages/EditMyAbout.jsx
  src/pages/EditMyInfo.jsx
Labels: 🌿haydenCho, ✔️FIX

#98 [UPDATE] 마이페이지 프로필
  src/components/HeaderMyPage.jsx
Labels: 🌿haydenCho

#101 [UPDATE] 자잘한 수정(프로필 관련)
  src/pages/DetailActivity.jsx
  src/pages/NewActivity.jsx
  src/pages/Notification.jsx
Labels: 🌿haydenCho
